title: Marco Castelluccio
author: Marco Castelluccio
email: mcastelluccio@mozilla.com

theme: minima

github_username: marco-c
rss: rss

plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - sources
